### PR TITLE
Added Code for the Net Gun

### PR DESCRIPTION
**Pull request by ghost**
The code is added for the Net Gun.
Shoot down an enemy delivery drone when it is in Scope

### CODE REVIEW

**Review by youn0125 — COMMENTED** [review]
Do we have to break for loop after shooting?

**Comment by ghost** [comment]
> Do we have to break for loop after shooting?

Once the drone is shot down, it checks for other enemy drones in its range. If there are none, it breaks

**Review by tollesonpdx — APPROVED** [review]
It will be cool to see this in use against drones

**Review by tollesonpdx — COMMENTED** [review]
I'm with Mi Yon, I'm not sure the break is necessary but I also don't know if it is problematic at all.

**Comment by youn0125** [comment]
I think if you want to shoot all of the enemy drones, you have to remove break. If you break, you shoot just one enemy drone and exit the loop.

**Comment by ghost** [comment]
> I think if you want to shoot all of the enemy drones, you have to remove break. If you break, you shoot just one enemy drone and exit the loop.

What my thinking is that the break is inside the if loop which just shoots down drones once. After it breaks it will be still inside the for loop which checks for other enemy drones. If it finds an enemy drone, it will again go inside the if loop to shoot it down.

**Comment by youn0125** [comment]
Is the break statment for break the if statement? If it is, the break statement only exits the loop like for, while... something like this. So, if you break in the if statement, it will exit the for loop. I wasn't sure about the break statement, so I googled it and found this. https://stackoverflow.com/questions/28731588/breaking-out-of-nested-if

**Comment by ghost** [comment]
> Is the break statment for break the if statement? If it is, the break statement only exits the loop like for, while... something like this. So, if you break in the if statement, it will exit the for loop. I wasn't sure about the break statement, so I googled it and found this. https://stackoverflow.com/questions/28731588/breaking-out-of-nested-if

Hmm, Seems logical. Okay, I will remove the break. If in the case in future we encounter any issue we shall look into it. Thanks for the link and sharing yon.

**Pull request closed without merging**
